"""add chat history and ocr tables

Revision ID: 7105fcbab4fd
Revises: 9b3c1d7e5a42
Create Date: 2026-05-08 21:48:09.737201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7105fcbab4fd'
down_revision: Union[str, Sequence[str], None] = '9b3c1d7e5a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_message',
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('chat_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('menu_list',
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('menu_name', sa.String(length=255), nullable=False),
    sa.Column('menu_price', sa.Integer(), nullable=False),
    sa.Column('upload_time_stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('ocr_data',
    sa.Column('ocr_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('pic_no', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['pic_no'], ['picture.unique_id'], ),
    sa.PrimaryKeyConstraint('ocr_no')
    )
    op.create_index(op.f('ix_ocr_data_uuid'), 'ocr_data', ['uuid'], unique=False)
    op.create_table('user_message',
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('chat_order', sa.Integer(), nullable=False),
    sa.Column('picture_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['picture_id'], ['picture.unique_id'], ),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('chats',
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('user_msg_id', sa.String(length=36), nullable=True),
    sa.Column('ai_msg_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ai_msg_id'], ['ai_message.unique_id'], ),
    sa.ForeignKeyConstraint(['user_msg_id'], ['user_message.unique_id'], ),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_index(op.f('ix_chats_uuid'), 'chats', ['uuid'], unique=False)
    op.create_table('ocr_menu_array',
    sa.Column('data_no', sa.Integer(), nullable=False),
    sa.Column('menu_no', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['data_no'], ['ocr_data.ocr_no'], ),
    sa.ForeignKeyConstraint(['menu_no'], ['menu_list.unique_id'], ),
    sa.PrimaryKeyConstraint('data_no', 'menu_no')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('ocr_menu_array')
    op.drop_index(op.f('ix_chats_uuid'), table_name='chats')
    op.drop_table('chats')
    op.drop_table('user_message')
    op.drop_index(op.f('ix_ocr_data_uuid'), table_name='ocr_data')
    op.drop_table('ocr_data')
    op.drop_table('menu_list')
    op.drop_table('ai_message')
    # ### end Alembic commands ###
