"""init schema

Revision ID: 7f8ad0a9eb9c
Revises: 
Create Date: 2026-05-02 10:59:57.565485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8ad0a9eb9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_array',
    sa.Column('clusterno', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('clusterno')
    )
    op.create_table('metadata',
    sa.Column('uniqueid', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uniqueid')
    )
    op.create_table('tags',
    sa.Column('tagstring', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('tagstring')
    )
    op.create_table('cluster_tags',
    sa.Column('cluster_no', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['cluster_no'], ['cluster_array.clusterno'], ),
    sa.ForeignKeyConstraint(['tag'], ['tags.tagstring'], ),
    sa.PrimaryKeyConstraint('cluster_no', 'tag')
    )
    op.create_table('picture',
    sa.Column('uniqueid', sa.Integer(), nullable=False),
    sa.Column('pic_name', sa.String(length=255), nullable=False),
    sa.Column('serving_pic_name', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('metadata_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['metadata_id'], ['metadata.uniqueid'], ),
    sa.PrimaryKeyConstraint('uniqueid')
    )
    op.create_table('cluster_pictures',
    sa.Column('cluster_no', sa.Integer(), nullable=False),
    sa.Column('pic_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_no'], ['cluster_array.clusterno'], ),
    sa.ForeignKeyConstraint(['pic_no'], ['picture.uniqueid'], ),
    sa.PrimaryKeyConstraint('cluster_no', 'pic_no')
    )
    op.create_table('picture_tags',
    sa.Column('pic_no', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['pic_no'], ['picture.uniqueid'], ),
    sa.ForeignKeyConstraint(['tag'], ['tags.tagstring'], ),
    sa.PrimaryKeyConstraint('pic_no', 'tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picture_tags')
    op.drop_table('cluster_pictures')
    op.drop_table('picture')
    op.drop_table('cluster_tags')
    op.drop_table('tags')
    op.drop_table('metadata')
    op.drop_table('cluster_array')
    # ### end Alembic commands ###
