"""v2 normalized schema

Revision ID: e90a28fc76ee
Revises: 
Create Date: 2026-05-08 01:23:05.214170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90a28fc76ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_array',
    sa.Column('cluster_no', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('cluster_no')
    )
    op.create_table('image',
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=True),
    sa.Column('s3_key', sa.String(length=255), nullable=True),
    sa.Column('s3_version', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('metadata',
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('tags',
    sa.Column('tag_string', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('tag_string')
    )
    op.create_table('picture',
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('image_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.unique_id'], ),
    sa.ForeignKeyConstraint(['metadata_id'], ['metadata.unique_id'], ),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('tag_list',
    sa.Column('cluster_no', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['cluster_no'], ['cluster_array.cluster_no'], ),
    sa.ForeignKeyConstraint(['tag'], ['tags.tag_string'], ),
    sa.PrimaryKeyConstraint('cluster_no', 'tag')
    )
    op.create_table('per_pic_tags',
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['tag'], ['tags.tag_string'], ),
    sa.ForeignKeyConstraint(['unique_id'], ['picture.unique_id'], ),
    sa.PrimaryKeyConstraint('unique_id', 'tag')
    )
    op.create_table('picture_list',
    sa.Column('cluster_no', sa.Integer(), nullable=False),
    sa.Column('pic_no', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['cluster_no'], ['cluster_array.cluster_no'], ),
    sa.ForeignKeyConstraint(['pic_no'], ['picture.unique_id'], ),
    sa.PrimaryKeyConstraint('cluster_no', 'pic_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picture_list')
    op.drop_table('per_pic_tags')
    op.drop_table('tag_list')
    op.drop_table('picture')
    op.drop_table('tags')
    op.drop_table('metadata')
    op.drop_table('image')
    op.drop_table('cluster_array')
    # ### end Alembic commands ###
